/* 检验订单详情 */
export default {
  // 修改订单信息
  SET_ORDER: 'SET_ORDER',
  // 添加检验项目
  ADD_CHECKORDERPROJECT: 'ADD_CHECKORDERPROJECT',
  // 删除基本项目
  DELETE_CHECKPROJECT: 'DELETE_CHECKPROJECT',
  // 删除组合项目
  DELETE_CHECKSETPROJECT: 'DELETE_CHECKSETPROJECT',
  // 清空新项目列表
  CLEAR_NEWPROJECTLST: 'CLEAR_NEWPROJECTLST',
  // 更新图片信息
  UPDATE_IMGS: 'UPDATE_IMGS',
  // 设置付款方式
  SET_PAYTYPE: 'SET_PAYTYPE'
}