export default {
  //诊所id
  SET_CLINICID: 'SET_CLINICID',
  //更改患者信息
  SET_PATIENT: 'SET_PATIENT',
  //设置医生ID
  SET_DOCTORID: 'SET_DOCTORID',

  /* 检验订单详情 */
  SET_CONFIRMEDPATIENT: 'SET_CONFIRMEDPATIENT'
}
