export default {
  //诊所id
  SET_CLINICID: 'SET_CLINICID',
  //更改患者信息
  SET_PATIENT: 'SET_PATIENT',
  //设置医生ID
  SET_DOCTORID: 'SET_DOCTORID',
  //新增项目
  PUSH_CHECKITEM: 'PUSH_CHECKITEM',
  //删除检查项目
  DELETE_CHECKITEM: 'DELETE_CHECKITEM',
  //增加管类型
  PUSH_CONTAIN: 'PUSH_CONTAIN',
  //删除管类型
  DELETE_CONTAIN: 'DELETE_CONTAIN',
  //清空管类型
  CLEAR_CONTAIN: 'CLEAR_CONTAIN',
  //替换更新管类型
  SET_CONTAIN: 'SET_CONTAIN'
}
